name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@< version >
      with:
        java-version: 8
        maven-version: ${{ matrix.maven }}
    - run: mvn install
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag demo:$(date +%s)
