name: Maven Package

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Push directory to another repository
      # You may pin to the exact commit or the version.
      # uses: cpina/github-action-push-to-another-repository@07c4d7b3def0a8ebe788a8f2c843a4e1de4f6900
      uses: cpina/github-action-push-to-another-repository@v1.7.2
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_GITHUB_TOKEN }}
      with:
        # Source before directory from the origin directory
        source-before-directory: deployment
        # Source directory from the origin directory
        source-directory: deployment
        # Name of the destination username/organization
        destination-github-username: paulopanini
        # Destination repository
        destination-repository-name: microservice-configurations
        # Email for the git commit
        user-email: paulopanini@gmail.com
        # [Optional] commit message for the output repository. ORIGIN_COMMIT is replaced by the URL@commit in the origin repo
        commit-message: Adding demo to IAC
        # [Optional] The directory to wipe and replace in the target repository
        target-directory: demo


