name: Maven Package

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - run: ls
    - run: git clone https://$${{ secrets.API_TOKEN_GITHUB }}@github.com/paulopanini/microservice-configurations.git
    - run: git remote set-url origin https://$${{ secrets.API_TOKEN_GITHUB }}@github.com/paulopanini/microservice-configurations.git
    - run: git config --global user.email "backstage@benify.com"
    - run: git config --global user.name "backstage"
    - run: ls
    - run: cd microservice-configurations
    - run: mkdir demo
    - run: ls
    - run: cp -a ../deployment/. demo/
    - run: git add .
    - run: git commit -m "Adding demo to IAC"
    - run: git push



