name: Maven Package

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: '.'
        file: ./Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/${{ github.repository_owner }}/demo:latest

  deploy-uat: 
    if: "contains(github.event.head_commit.message, '#deployuat')"
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write

    steps:
    - run: git clone https://token:${{ secrets.API_GITHUB_TOKEN }}@github.com/paulopanini/microservice-configurations.git
    - run: git remote set-url origin https://token:${{ secrets.API_GITHUB_TOKEN }}@github.com/paulopanini/microservice-configurations.git
    - run: git config --global user.email "backstage@benify.com"
    - run: git config --global user.name "backstage"
    - run: cd microservice-configurations/demo
    - run: sed -i -E "s/(hello-world:)[a-z|0-9]*/demo:$CI_COMMIT_SHORT_SHA/g" deployment.yaml
    - run: git add .
    - run: git commit -m "Deploy $CI_COMMIT_TIMESTAMP"
    - run: git push

  first-deploy:
    if: "contains(github.event.head_commit.message, '#backstage')"
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Handle first deploy
      uses: cpina/github-action-push-to-another-repository@v1.7.2
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_GITHUB_TOKEN }}
      with:
        source-before-directory: deployment
        source-directory: deployment
        destination-github-username: paulopanini
        destination-repository-name: microservice-configurations
        user-email: paulopanini@gmail.com
        commit-message: Adding demo to IAC
        target-directory: demo


