name: Maven Package

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - run: ls
    - name: Copy files to another repository
      # You may pin to the exact commit or the version.
      # uses: nkoppel/push-files-to-another-repository@993c4b2dae204519735dd914c24dd6f1d2acd24d
      uses: nkoppel/push-files-to-another-repository@v1.1.1
      env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        # The files/directories to copy to the destination repository. Can have multiple space-separated filenames and globbing.
        source-files: deploymet/
        # Name of the destination username/organization
        destination-username: paulopanini
        # Name of the destination repository
        destination-repository: microservice-configurations
        # Email for the commit
        commit-email: paulo.panini@benify.com
        destination-branch: main
