name: Maven Package

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - run: ls
    - name: Push generated webpage to another repository
      uses: nkoppel/push-files-to-another-repository@1.1.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-files: 'deployment/'
        destination-username: 'paulopanini'
        destination-repository: 'microservice-configurations'
        destination-directory: 'demo'
        commit-email: 'paulo.panini@benify.com'
    
