name: Maven Package

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - run: ls
    - run: git clone https://$${{ secrets.GITHUB_TOKEN  }}@github.com/paulopanini/microservice-configurations.git
    - run: git remote set-url origin https://$${{ secrets.GITHUB_TOKEN  }}@github.com/paulopanini/microservice-configurations.git
    - run: git config --global user.email "backstage@benify.com"
    - run: git config --global user.name "backstage"
    - run: mkdir demo
    - run: ls
    - run: cp -a deployment/. microservice-configurations/demo/
    - run: cd microservice-configurations && git config --unset-all https://github.com/.extraheader && git remote set-url origin https://paulopanini:$${{ secrets.GITHUB_TOKEN  }}@github.com/paulopanini/microservice-configurations.git && git add . && git commit -m "Adding demo to IAC" && git push



